/**
 * Alipay.com Inc.
 * Copyright (c) 2004-2012 All Rights Reserved.
 */
package com.brucexx.aries.tag;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.BeanDefinitionStoreException;
import org.springframework.beans.factory.support.AbstractBeanDefinition;
import org.springframework.beans.factory.xml.AbstractSimpleBeanDefinitionParser;
import org.springframework.beans.factory.xml.ParserContext;
import org.w3c.dom.Element;

/**
 * 
 * @author zhao.xiong
 * @version $Id: ServiceParser.java, v 0.1 2012-5-24 ÏÂÎç03:41:17 zhao.xiong Exp $
 */
public class ServiceParser extends AbstractSimpleBeanDefinitionParser {

    private static Logger logger = Logger.getLogger("aries-core");

    @SuppressWarnings("rawtypes")
    protected Class getBeanClass(Element element) {
        String _interface = element.getAttribute("interface");
        try {
            return Class.forName(_interface);
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
    }

    private static int n = 0;

    protected String resolveId(Element element, AbstractBeanDefinition definition,
                               ParserContext parserContext) throws BeanDefinitionStoreException {
        String refBean = element.getAttribute("ref");
        String _interface = element.getAttribute("interface");
        String protocol = element.getAttribute("protocol");
        String id = getId(element);
        ServiceModel sm = new ServiceModel();
        sm.setId(id);
        sm.setRefBean(refBean);
        sm.setInterface(_interface);
        sm.setProtocol(protocol);

        TagModelCache.putService(sm);
        logger.info("register service ==>" + sm);
        return sm.getId();
    }

    private String getId(Element element) {
        if (StringUtils.isEmpty(element.getAttribute("id"))) {
            return "autoGeneratedPropertyBeanId_" + n++;
        }
        return element.getAttribute("id");
    }

}
