/**
 * Alipay.com Inc.
 * Copyright (c) 2004-2012 All Rights Reserved.
 */
package com.brucexx.springtag;

import org.springframework.beans.factory.BeanDefinitionStoreException;
import org.springframework.beans.factory.support.AbstractBeanDefinition;
import org.springframework.beans.factory.xml.AbstractSimpleBeanDefinitionParser;
import org.springframework.beans.factory.xml.ParserContext;
import org.springframework.util.StringUtils;
import org.w3c.dom.Element;

import com.brucexx.tagbean.ServiceTagBean;

/**
 * 
 * @author zhao.xiong
 * @version $Id: ServiceParser.java, v 0.1 2012-5-24 ÏÂÎç03:41:17 zhao.xiong Exp $
 */
public class ServiceParser extends AbstractSimpleBeanDefinitionParser {

	@SuppressWarnings("rawtypes")
	protected Class getBeanClass(Element element) {
		return ServiceTagBean.class;
	}

	private static int n = 0;

	protected String resolveId(Element element,
			AbstractBeanDefinition definition, ParserContext parserContext)
			throws BeanDefinitionStoreException {
		String id = super.resolveId(element, definition, parserContext);
		System.out.println("good id:" + id);
		if (StringUtils.hasText(id))
			return id;
		return "autoGeneratedPropertyBeanId_" + n++;
	}
}
